export enum App {
    ADMINISTRATOR = 'ADMINISTRATOR',
    PROFESSIONAL = 'PROFESSIONAL',
    PARTNER_CLINIC = 'PARTNER_CLINIC',
    PARTNER_COMMERCIAL = 'PARTNER_COMMERCIAL',
    RECEPTIONIST = 'RECEPTIONIST'
}