export enum ModelType {
    MESSAGE = "MESSAGE",
    PUBLICATION = "PUBLICATION",
    CHAT = "CHAT",
    ORDER = "ORDER",
    COMMENT = "COMMENT",
    COMMUNITY = "COMMUNITY",
    CHARGE = "CHARGE",
    EVENT = "EVENT",
    CLIENT = "CLIENT",
    PARTNER = "PARTNER",
    ADMINISTRATOR = "ADMINISTRATOR",
    LIKE = "LIKE",
    FOLLOWER = "FOLLOWER",
    WEBSOCKET_CONNECTION = "WEBSOCKET_CONNECTION"
}