export enum OrderStatus {
    WAITING_PAYMENT = "WAITING_PAYMENT",
    PROCESSING = "PROCESSING",
    SHIPPED = "SHIPPED",
    DELIVERED = "DELIVERED",
    CONCLUDED = "CONCLUDED",
    CANCELED = "CANCELED"
}