export enum PaymentStatus {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    INPROCESS = "INPROCESS",
    INMEDIATION = "INMEDIATION",
    REJECTED = "REJECTED",
    CANCELLED = "CANCELLED",
    REFUNDED = "REFUNDED",
    CHARGEDBACK = "CHARGEDBACK"
}