export enum Route {
	CALLBACK = 'callback',
	CHATS = 'chats',
	CLIENTS = 'clients',
	DASHBOARD = 'dashboard',
	FOLLOWERS = 'followers',
	MARKETPLACE = 'marketplace',
	MEDICAL_APPOINTMENTS_EXTRACT = 'medical-appointments-extract',
	MEDICAL_INSURANCES = 'medical-insurances',
	MEDICAL_RECORD = 'medical-record/:id',
	MEDICAL_SCHEDULE = 'medical-schedule',
	ORDERS = 'orders',
	PROCEDURES = 'procedures',
	PROFESSIONALS = 'professionals',
	PROFILE = 'profile',
	PUBLICATIONS = 'publications',
	SCHEDULE = 'schedule',
	SIGN_IN = 'sign-in',
	SIGN_UP = 'sign-up',
}
