export enum Route {
	CALLBACK = 'callback',
	CHAT = 'chats/:id',
	CHATS = 'chats',
	CLIENTS = 'clients',
	DASHBOARD = 'dashboard',
	FOLLOWERS = 'followers',
	MARKETPLACE = 'marketplace',
	MEDICAL_APPOINTMENTS_EXTRACT = 'medical-appointments-extract',
	MEDICAL_INSURANCES = 'medical-insurances',
	MEDICAL_RECORD = 'medical-record/:id',
	MEDICAL_SCHEDULE = 'medical-schedule',
	ORDER = 'orders/:id',
	ORDERS = 'orders',
	PROCEDURES = 'procedures',
	PRODUCT_DETAILS = 'products/:id',
	PRODUCT_REGISTER = 'products/register',
	PRODUCT_UPDATE = 'products/:id/update',
	PROFESSIONALS = 'professionals',
	PROFILE = 'profile',
	PUBLICATIONS = 'publications',
	SCHEDULE = 'schedule',
	SERVICE_DETAILS = 'services/:id',
	SERVICE_REGISTER = 'services/register',
	SERVICE_UPDATE = 'services/:id/update',
	SIGN_IN = 'sign-in',
	SIGN_UP = 'sign-up',
}
